# Welcome to Jekyll!
#

# Site settings
title: Eugenio Felix
description: |
  Front-End Developer & Graphic Designer
owner: Eugenio Felix # or company name
first_published: 2016 # if migrating another site, the year of your first publish
email: eugeniofr11@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
social:
  #twitter: https://twitter.com/<username>
  #email: mailto:eugeniofr11@gmail.com
  behance: http://www.behance.net/eugeniofr
  linkedin-square: https://www.linkedin.com/in/eugenio-felix-bb7829bb
  angellist: https://angel.co/eugenio-felix
  flickr: https://www.flickr.com/photos/130838846@N03/
  deviantart: http://eugenio1.deviantart.com/
  github: https://github.com/eugeniofr
  linkedin-square: https://www.linkedin.com/in/eugenio-felix-bb7829bb
  #facebook-official: https://facebook.com/<username>
  #google-plus-square: https://plus.google.com/u/0/+<username>
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
